import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import numpy as np
import pickle
import os

# Load pickled traj data (generated by load_dumps.py)
traj_path = os.path.expanduser("~/AMPT/dumps/traj.pkl")
if not os.path.exists(traj_path):
    raise FileNotFoundError(f"Pickle file '{traj_path}' not found. Run load_dumps.py first.")

with open(traj_path, "rb") as f:
    traj = pickle.load(f)

traj.sort(key=lambda tup: tup[0])  # sort by timestep

# Species color mapping
type_to_color = {1: 0, 2: 1}  # map species type to color index
colors_cycle = plt.rcParams['axes.prop_cycle'].by_key()['color']

# Optional: subsample for speed
subsample = 5000
def get_frame_data(df):
    if subsample and len(df) > subsample:
        return df.sample(subsample, random_state=0)
    return df

# Get box extents from first frame
_, _, box0 = traj[0]
xlim = (box0['xlo'], box0['xhi'])
ylim = (box0['ylo'], box0['yhi'])
zlim = (box0['zlo'], box0['zhi'])

# Set up 3D plot
fig = plt.figure(figsize=(6, 5))
ax = fig.add_subplot(projection='3d')
scat = ax.scatter([], [], [], s=2)

ax.set_xlim(*xlim)
ax.set_ylim(*ylim)
ax.set_zlim(*zlim)
ax.set_xlabel("x (m)")
ax.set_ylabel("y (m)")
ax.set_zlabel("z (m)")
title = ax.set_title("")

def init():
    scat._offsets3d = ([], [], [])
    return scat,

def update(frame_idx):
    step, df, _ = traj[frame_idx]
    dff = get_frame_data(df)
    x = dff['x'].values
    y = dff['y'].values
    z = dff['z'].values
    t = dff['type'].astype(int).map(type_to_color).fillna(0).values
    c = [colors_cycle[i % len(colors_cycle)] for i in t]
    scat._offsets3d = (x, y, z)
    scat.set_color(c)
    title.set_text(f"Step {step}")
    return scat, title

ani = FuncAnimation(fig, update, frames=len(traj), init_func=init, blit=False, interval=200)
ani.save("particle_anim.mp4", fps=5, dpi=150)
