#!/usr/bin/env python3
import numpy as np
import os
import sys
import matplotlib.pyplot as plt

# get altitude from command line or use default
if len(sys.argv) > 1:
    alt = float(sys.argv[1])
else:
    alt = 85.0  # default

print(f"Using altitude: {alt} km")

# determine correct paths based on script location
script_dir = os.path.dirname(os.path.abspath(__file__))
ampt_dir = os.path.dirname(script_dir)  # Parent of tools directory
data_dir = os.path.join(ampt_dir, 'data')

# check if NRLMSIS data file exists, if not create it
data_file = os.path.join(data_dir, 'nrlmsis.dat')
if not os.path.exists(data_file):
    print(f"NRLMSIS data file not found. Generating fresh data...")
    
    try:
        import pymsis
        import datetime
        import scipy.constants as const
        
        # constants
        R_E = 6378e3  # m
        mu_E = 3.986e14 # m^3/s^2
        k_B = 1.380649e-23 # J/K
        R = 287.05 # specific gas constant, air (J / kg*K)
        
        lat = 40.7934
        lon = -77.8600
        altitudes = np.linspace(70e3, 300e3, 501)  # m
        alt_km = altitudes * 1e-3  # km
        
        # load NRLMSIS Data
        utc = datetime.datetime(2011, 4, 10, 0, 0)  # Day 100, midnight (matches Ethan's sec=0)
        times = np.array([utc], dtype='datetime64')
        
        # Ethan solar/geomagnetic params
        f107a = 250  # 81-day average F10.7
        f107 = 250   # daily F10.7
        aps = [[4, 4, 4, 4, 4, 4, 4]]  # Ap indices: [daily, 0h, 3h, 6h, 9h, 12-33h avg, 36-57h avg]
        
        msis_version = 2.1
        atmosphere = pymsis.calculate(times, [lon], [lat], alt_km, 
                                     f107, f107a, aps,
                                     version=msis_version)
        
        T = np.squeeze(atmosphere[..., pymsis.Variable.TEMPERATURE])
        rho = np.squeeze(atmosphere[..., pymsis.Variable.MASS_DENSITY])
        P = rho * R * T
        P_torr = P / 133.322
        v = np.sqrt(mu_E / (R_E + altitudes))
        N = P / (k_B * T)

        # species number densities
        n_N2 = np.squeeze(atmosphere[..., pymsis.Variable.N2])
        n_O2 = np.squeeze(atmosphere[..., pymsis.Variable.O2])
        n_O  = np.squeeze(atmosphere[..., pymsis.Variable.O])
        n_He = np.squeeze(atmosphere[..., pymsis.Variable.HE])
        n_Ar = np.squeeze(atmosphere[..., pymsis.Variable.AR])
        n_N  = np.squeeze(atmosphere[..., pymsis.Variable.N])

        plt.figure(figsize=(8, 5))
        plt.plot(alt_km, rho)
        plt.xlabel('Altitude (km)')
        plt.ylabel('Density (kg/m³)')
        plt.title('Density vs Altitude')
        plt.grid(True)
        
        # save data to file
        data = np.column_stack((alt_km, T, rho, P, P_torr, v, N, n_N2, n_O2, n_O, n_He, n_Ar, n_N))
        header = "Altitude_km Temperature_K Density_kg_m3 Pressure_Pa Pressure_Torr Orbital_Velocity_m_s Number_Density_per_m3 n_N2 n_O2 n_O n_He n_Ar n_N"
        
        os.makedirs(data_dir, exist_ok=True)
        np.savetxt(data_file, data, header=header, fmt='%.6e', delimiter=' ')
        print(f"Generated NRLMSIS data and saved to {data_file}")
        
    except ImportError:
        print("ERROR: pymsis not available. Using existing data file if present, or create data manually.")
        if not os.path.exists(data_file):
            print(f"ERROR: No NRLMSIS data file found at {data_file}")
            exit(1)

# load NRLMSIS data
d = np.loadtxt(data_file)

# interpolate values for specified altitude
os.makedirs(data_dir, exist_ok=True)
rho_val = np.interp(alt, d[:,0], d[:,2])
nrho_val = np.interp(alt, d[:,0], d[:,6])
T_val = np.interp(alt, d[:,0], d[:,1])
vx_val = np.interp(alt, d[:,0], d[:,5])

# species fractions
# columns: 7=n_N2, 8=n_O2, 9=n_O, 10=n_He, 11=n_Ar, 12=n_N
n_N2 = np.interp(alt, d[:,0], d[:,7])
n_O2 = np.interp(alt, d[:,0], d[:,8])
n_O  = np.interp(alt, d[:,0], d[:,9])
n_He = np.interp(alt, d[:,0], d[:,10])
n_Ar = np.interp(alt, d[:,0], d[:,11])
n_N  = np.interp(alt, d[:,0], d[:,12])

# replace nan with 0 (pymsis returns nan for some species at low altitudes)
n_N2 = np.nan_to_num(n_N2)
n_O2 = np.nan_to_num(n_O2)
n_O  = np.nan_to_num(n_O)
n_He = np.nan_to_num(n_He)
n_Ar = np.nan_to_num(n_Ar)
n_N  = np.nan_to_num(n_N)

n_total = n_N2 + n_O2 + n_O + n_He + n_Ar + n_N
frac_N2 = round(n_N2 / n_total, 4)
frac_O2 = round(n_O2 / n_total, 4)
frac_O  = round(n_O / n_total, 4)
frac_He = round(n_He / n_total, 4)
frac_Ar = round(n_Ar / n_total, 4)
frac_N  = 1.0 - (frac_N2 + frac_O2 + frac_O + frac_He + frac_Ar)

# write sparta include file with all atmospheric data
with open(os.path.join(data_dir, 'atm.sparta'), 'w') as f:
    f.write(f"# NRLMSIS-{msis_version} atmospheric data for {alt} km altitude\n")
    f.write(f"# Generated by load_atm_data.py\n\n")
    f.write(f"variable        rho  equal {rho_val:.12e}\n")
    f.write(f"variable        nrho equal {nrho_val:.6e}\n")
    f.write(f"variable        T    equal {T_val:.6f}\n")
    f.write(f"variable        vx   equal {vx_val:.1f}\n\n")
    f.write(f"species         species/air.species N2 O2 O He Ar N\n")
    f.write(f"mixture         atm N2 frac {frac_N2:.4f}\n")
    f.write(f"mixture         atm O2 frac {frac_O2:.4f}\n")
    f.write(f"mixture         atm O  frac {frac_O:.4f}\n")
    f.write(f"mixture         atm He frac {frac_He:.4f}\n")
    f.write(f"mixture         atm Ar frac {frac_Ar:.4f}\n")
    f.write(f"mixture         atm N  frac {frac_N:.4f}\n")

print(f'Loaded atmospheric data for {alt} km altitude')
print(f'  rho: {rho_val:.3e} kg/m³')
print(f'  nrho: {nrho_val:.3e} m⁻³')
print(f'  T: {T_val:.1f} K')
print(f'  vx: {vx_val:.1f} m/s')
print(f'  N2: {frac_N2:.4f}  O2: {frac_O2:.4f}  O: {frac_O:.4f}  He: {frac_He:.4f}  Ar: {frac_Ar:.4f}  N: {frac_N:.4f}')
